import { Metadata } from 'next';
import ArticleLayout from "@/components/blog/article-layout";

export const metadata: Metadata = {
  title: "How Writing Telemetry Visualizes Revision Bursts vs. Retyping | Checkmark Plagiarism",
  description: "Discover how writing telemetry and keystroke dynamics visualize authentic revision bursts (R-bursts) versus mechanical second-screen retyping, empowering educators with transparent, defensible writing process evidence.",
  keywords: [
    "writing telemetry",
    "revision bursts",
    "mechanical retyping",
    "keystroke dynamics",
    "Essay Playback",
    "Inter-Key Intervals",
    "P-bursts",
    "R-bursts",
    "transcription detection",
    "Checkmark Plagiarism",
    "academic integrity",
    "AI detection",
    "second-screen evasion",
    "cognitive writing process"
  ],
  openGraph: {
    images: [
      "/images/services/report-paste-evidence.png",
      "/images/services/report-originality-tiles.png",
    ],
  },
};

const meta = {
  title: "How Writing Telemetry Visualizes Revision Bursts Versus Mechanical Retyping in Student Essays | Checkmark Plagiarism",
  description: "Discover how writing telemetry and keystroke dynamics visualize authentic revision bursts (R-bursts) versus mechanical second-screen retyping, empowering educators with transparent, defensible writing process evidence.",
  "opengraph-image": "/images/services/report-paste-evidence.png",
  date: "08-18-2026",
  readTime: "~15 min read",
  category: "Writing Process",
  categories: ["Writing Process", "Detection", "How It Works", "Teacher Guide", "Pedagogy"],
  author: "The Checkmark Plagiarism Team",
};

const bodyHtml = `
<!-- Executive Summary Callout Box -->
<div class="my-6 rounded-2xl bg-teal-500/10 border border-teal-500/20 p-6 text-foreground shadow-sm">
  <div class="flex items-center gap-2 mb-2">
    <span class="inline-flex h-2.5 w-2.5 rounded-full bg-teal-500 animate-pulse"></span>
    <p class="text-xs font-bold uppercase tracking-wider text-teal-700 dark:text-teal-400">Executive Summary</p>
  </div>
  <p class="text-base text-foreground leading-relaxed">
    As students discover that traditional automated clipboard monitors flag large block copy-pastes, a growing number turn to a more covert evasion strategy: <strong>manual optical transcription</strong>, where text generated by an external Large Language Model (LLM) on a smartphone, tablet, or secondary monitor is manually retyped into the document editor. Standard plagiarism scanners and static AI detectors struggle with these submissions because no paste event is logged and surface syntax may be modified. However, genuine human composition and optical transcription leave fundamentally different biometric and psycholinguistic footprints in document telemetry. Authentic writing is intrinsically non-linear—defined by high Inter-Key Interval (IKI) variance, production bursts (P-bursts) at syntactic thresholds, cognitive planning pauses (2–15+ seconds), and recursive revision bursts (R-bursts) that restructure sentences and delete whole thoughts (12%–30% friction ratio). Conversely, mechanical retyping exhibits a metronomic, invariant typing cadence, narrow IKI distributions, strictly linear progression (0 &rarr; N), and zero conceptual restructuring. Checkmark Plagiarism&apos;s patent-pending <strong><a href="/services/writing-playback" class="text-teal-600 dark:text-teal-400 underline font-semibold">Essay Playback™</a></strong> suite captures these dynamics through 1x–8x chronological video replay, automated Transcription Detection Indicators, full clipboard text preservation, and an integrated multi-factor verification triad. Grounded in the philosophy <strong>&ldquo;Stop guessing, start trusting,&rdquo;</strong> this telemetry equips educators to conduct supportive, evidence-based student conferences while offering bulletproof protection for honest students falsely accused by black-box detectors.
  </p>
</div>

<!-- Featured Visual Asset / Hero Report View -->
<div class="my-8 rounded-2xl overflow-hidden border border-border shadow-lg bg-card">
  <img 
    src="/images/services/report-paste-evidence.png" 
    alt="Checkmark Plagiarism Writing Process Telemetry and Keystroke Playback Interface" 
    class="w-full h-auto object-cover m-0"
  />
  <div class="p-4 bg-muted/40 border-t border-border text-xs text-muted-foreground flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
    <span><strong>Figure 1.0:</strong> Checkmark Writing Process Forensics — Timestamped Revision Bursts, Paste Buffer Preservation, and Synchronized Velocity Curves.</span>
    <span class="text-teal-600 dark:text-teal-400 font-medium">Patent-Pending Essay Playback™</span>
  </div>
</div>

<h2>1. The Modern Evasion Dilemma: The Rise of Second-Screen Optical Transcription</h2>

<p>
  In the initial wave of generative artificial intelligence in education, academic integrity inquiries typically focused on raw clipboard actions. A student prompted a conversational AI model, copied several paragraphs, pasted the entire block directly into their Learning Management System (LMS) essay box or Google Docs, and clicked submit.
</p>

<p>
  Educators and basic integrity tools quickly learned to identify these submissions through straightforward indicators:
</p>

<ul>
  <li>Single-timestamp block insertions of 500 to 1,500 words appearing in under a second.</li>
  <li>Inconsistent font formatting, background HTML artifacts, or non-standard Unicode characters.</li>
  <li>Document edit histories showing a total active drafting time of under three minutes for a multi-page essay.</li>
</ul>

<h3>The Shift to Manual Retyping</h3>

<p>
  As students shared evasion tips on peer forums, social media channels, and discord servers, bypassing clipboard listeners became a routine objective. The prevailing workaround became <strong>optical transcription</strong> (commonly termed the <em>&ldquo;retype bypass&rdquo;</em> or <em>&ldquo;second-screen copying&rdquo;</em>).
</p>

<!-- Evasion Evolution Diagram -->
<div class="my-8 rounded-2xl bg-slate-900 text-slate-100 p-6 border border-slate-800 shadow-md">
  <div class="text-center font-bold text-teal-400 text-xs tracking-wider uppercase mb-6">The Evolution of Student AI Evasion Tactics</div>
  <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
    <!-- Generation 1 -->
    <div class="bg-slate-800/90 rounded-xl p-4 border border-slate-700 flex flex-col justify-between">
      <div>
        <div class="flex items-center justify-between mb-2">
          <span class="text-xs font-semibold text-rose-300">Generation 1</span>
          <span class="px-2 py-0.5 rounded bg-rose-500/20 text-rose-300 text-[10px] font-bold">Obsolete</span>
        </div>
        <h3 class="text-sm font-bold text-white mb-2 pt-0">Raw Block Paste</h3>
        <ul class="space-y-1.5 text-slate-300 text-xs list-disc pl-4">
          <li>Direct Ctrl+V into editor</li>
          <li>800 words inserted at 0.00s</li>
          <li>Easily caught by basic clipboard listeners</li>
          <li>Mismatched CSS/HTML formatting tags</li>
        </ul>
      </div>
      <div class="mt-4 pt-3 border-t border-slate-700/60 text-[11px] text-slate-400">
        <em>Intercepted by standard LMS logs</em>
      </div>
    </div>

    <!-- Generation 2 -->
    <div class="bg-slate-800/90 rounded-xl p-4 border border-slate-700 flex flex-col justify-between">
      <div>
        <div class="flex items-center justify-between mb-2">
          <span class="text-xs font-semibold text-amber-300">Generation 2</span>
          <span class="px-2 py-0.5 rounded bg-amber-500/20 text-amber-300 text-[10px] font-bold">Vulnerable</span>
        </div>
        <h3 class="text-sm font-bold text-white mb-2 pt-0">Text Humanizers</h3>
        <ul class="space-y-1.5 text-slate-300 text-xs list-disc pl-4">
          <li>Surface synonym swappers &amp; paraphrasers</li>
          <li>Attempts to evade perplexity / burstiness</li>
          <li>Still pasted into the editor as block text</li>
          <li>Produces unnatural sentence cadences</li>
        </ul>
      </div>
      <div class="mt-4 pt-3 border-t border-slate-700/60 text-[11px] text-slate-400">
        <em>Flagged by Checkmark Passage-Level AI Cards</em>
      </div>
    </div>

    <!-- Generation 3 -->
    <div class="bg-slate-800/90 rounded-xl p-4 border border-teal-500/50 flex flex-col justify-between ring-1 ring-teal-500/30">
      <div>
        <div class="flex items-center justify-between mb-2">
          <span class="text-xs font-semibold text-teal-300">Generation 3</span>
          <span class="px-2 py-0.5 rounded bg-teal-500/20 text-teal-300 text-[10px] font-bold">Current Evasion</span>
        </div>
        <h3 class="text-sm font-bold text-white mb-2 pt-0">Second-Screen Retyping</h3>
        <ul class="space-y-1.5 text-slate-300 text-xs list-disc pl-4">
          <li>Prompt LLM on mobile device or 2nd monitor</li>
          <li>Manually typed character-by-character</li>
          <li>Zero clipboard paste events logged</li>
          <li>Simulates 30–60 min active drafting session</li>
        </ul>
      </div>
      <div class="mt-4 pt-3 border-t border-slate-700/60 text-[11px] text-teal-300 font-semibold">
        <em>Definitively exposed by Keystroke Dynamics</em>
      </div>
    </div>
  </div>

  <div class="mt-6 p-4 rounded-xl bg-teal-950/40 border border-teal-500/30 text-center">
    <p class="text-xs text-teal-200">
      <strong>The Diagnostic Challenge:</strong> Zero clipboard paste events &plus; 45 minutes active session time &plus; Inconclusive static score &equals; Unprovable by legacy tools. Only writing process telemetry reveals the biometric truth.
    </p>
  </div>
</div>

<p>In an optical transcription workflow:</p>
<ol>
  <li>The student prompts an LLM (e.g., ChatGPT, Claude) on a separate device—such as a smartphone resting on their desk, a tablet positioned below their screen, or an adjacent browser window.</li>
  <li>Rather than copying and pasting the generated text, the student reads the text off the secondary display in 4-to-8-word eye-span chunks and manually types it into their document editor.</li>
  <li>If they make a minor motor typo, they tap the <code>Backspace</code> key once or twice, fix the immediate character error, and continue typing forward in a smooth, continuous sequence from the first sentence to the bibliography.</li>
</ol>

<h3>Why Traditional Diagnostic Methods Fail</h3>

<p>When evaluated by legacy academic integrity tools, optical transcription creates serious blind spots:</p>

<!-- Table of Traditional Failures -->
<div class="my-6 overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
  <div class="overflow-x-auto">
    <table class="w-full text-left text-xs border-collapse">
      <thead>
        <tr class="border-b border-border bg-muted/60 font-semibold text-foreground">
          <th class="p-3.5">Diagnostic Tool</th>
          <th class="p-3.5">What the Tool Sees</th>
          <th class="p-3.5">Why It Fails on Optical Retyping</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-border text-muted-foreground">
        <tr>
          <td class="p-3.5 font-medium text-foreground">Basic Clipboard / Paste Listeners</td>
          <td class="p-3.5">Logs zero <code>onPaste</code> DOM events.</td>
          <td class="p-3.5 text-rose-600 dark:text-rose-400">The text was physically typed character-by-character; no clipboard API was invoked.</td>
        </tr>
        <tr>
          <td class="p-3.5 font-medium text-foreground">Document Session Timers</td>
          <td class="p-3.5">Records 35 to 55 minutes of active document focus.</td>
          <td class="p-3.5 text-rose-600 dark:text-rose-400">The physical act of manual typing takes real time, creating an illusion of standard drafting effort.</td>
        </tr>
        <tr>
          <td class="p-3.5 font-medium text-foreground">Static AI Classifiers (Whole-Doc %)</td>
          <td class="p-3.5">Generates an opaque probability score (e.g., &ldquo;47% Likely AI&rdquo;).</td>
          <td class="p-3.5 text-rose-600 dark:text-rose-400">Static classifiers evaluate finished text in isolation. If the student swapped words or used a humanizer prompt, the score is ambiguous and indefensible in a conference.</td>
        </tr>
        <tr>
          <td class="p-3.5 font-medium text-foreground">Standard LMS Revision History</td>
          <td class="p-3.5">Shows periodic snapshots of text growing every few minutes.</td>
          <td class="p-3.5 text-rose-600 dark:text-rose-400">Generic revision histories aggregate changes into broad 5-to-10-minute snapshots, obscuring micro-cadence, pause dynamics, and cursor movements.</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<p>
  Despite evading superficial paste detectors, <strong>manual optical transcription cannot duplicate the cognitive psycholinguistics and biomechanics of authentic human writing</strong>. Composing original thoughts generates a distinct, measurable telemetry footprint of mental friction, planning pauses, and recursive structural revisions that differs fundamentally from mechanical transcription.
</p>

<hr class="my-8 border-border" />

<h2>2. Psycholinguistic &amp; Biomechanical Foundations: Composing vs. Transcribing</h2>

<p>
  To understand how writing telemetry separates genuine authorship from mechanical copying, we must review how the human brain produces written language.
</p>

<!-- Hayes-Flower & Kellogg Architecture Diagram -->
<div class="my-8 rounded-2xl bg-card border border-border p-6 shadow-sm">
  <div class="text-center font-bold text-foreground text-xs tracking-wider uppercase mb-6">The Hayes-Flower &amp; Kellogg Cognitive Writing Architecture</div>
  <div class="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
    <div class="rounded-xl bg-muted/40 p-4 border border-border">
      <div class="flex items-center gap-2 font-bold text-foreground text-sm mb-2">
        <span class="flex h-5 w-5 items-center justify-center rounded-full bg-teal-500/20 text-teal-600 dark:text-teal-400 text-xs">1</span>
        <span>Planning Subprocess</span>
      </div>
      <ul class="space-y-1.5 text-muted-foreground list-disc pl-4">
        <li>Idea retrieval from long-term memory</li>
        <li>Rhetorical framing &amp; outline structuring</li>
        <li>Assignment constraint evaluation</li>
        <li>Generates macro-planning pauses (2.0–15.0+ s)</li>
      </ul>
    </div>

    <div class="rounded-xl bg-muted/40 p-4 border border-border">
      <div class="flex items-center gap-2 font-bold text-foreground text-sm mb-2">
        <span class="flex h-5 w-5 items-center justify-center rounded-full bg-teal-500/20 text-teal-600 dark:text-teal-400 text-xs">2</span>
        <span>Translating Subprocess</span>
      </div>
      <ul class="space-y-1.5 text-muted-foreground list-disc pl-4">
        <li>Lexical selection &amp; syntactic assembly</li>
        <li>Motor execution (keystroke timing)</li>
        <li>Production bursts (P-bursts: 4–18 words)</li>
        <li>High Inter-Key Interval (IKI) variance</li>
      </ul>
    </div>

    <div class="rounded-xl bg-muted/40 p-4 border border-border">
      <div class="flex items-center gap-2 font-bold text-foreground text-sm mb-2">
        <span class="flex h-5 w-5 items-center justify-center rounded-full bg-teal-500/20 text-teal-600 dark:text-teal-400 text-xs">3</span>
        <span>Reviewing Subprocess</span>
      </div>
      <ul class="space-y-1.5 text-muted-foreground list-disc pl-4">
        <li>Error monitoring &amp; thesis evaluation</li>
        <li>Recursive revision bursts (R-bursts)</li>
        <li>Global re-ordering &amp; non-linear jumps</li>
        <li>Friction ratio DIR &equals; 12%–30%</li>
      </ul>
    </div>
  </div>

  <div class="mt-4 p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-center text-xs text-emerald-800 dark:text-emerald-300 font-medium">
    &larr; Non-Linear Recursive Loop: Writers continually cycle between Planning, Translating, and Reviewing &rarr;
  </div>
</div>

<p>
  In cognitive writing research—pioneered by John R. Hayes, Linda S. Flower, and Ronald T. Kellogg—authentic composition is established as a <strong>non-linear, recursive cognitive cycle</strong>. Writers do not produce fully formed prose in a single forward pass; they constantly loop between <em>Planning</em>, <em>Translating</em>, and <em>Reviewing</em>.
</p>

<h3>The Anatomy of Authentic Composing</h3>

<p>When a student authors an original essay, their working memory experiences intense cognitive load:</p>

<ol>
  <li><strong>Central Executive &amp; Long-Term Memory Retrieval:</strong> The student searches their memory for assignment requirements, historical evidence, rhetorical strategies, and subject knowledge.</li>
  <li><strong>Lexical Selection &amp; Syntactic Assembly:</strong> The writer formulates an idea, tests several sentence structures internally, hesitates over vocabulary choices, and translates conceptual thoughts into physical keystrokes.</li>
  <li><strong>Continuous Evaluative Feedback Loops:</strong> As words appear on screen, the writer reads their own output, recognizes stylistic flaws, logical gaps, or grammatical misalignments, and immediately revises.</li>
</ol>

<p>
  This cognitive friction manifests as two core biomechanical phenomena: <strong>Production Bursts (P-bursts)</strong> and <strong>Revision Bursts (R-bursts)</strong>.
</p>

<!-- Telemetry Waveform Visual Component -->
<div class="my-8 rounded-2xl bg-slate-950 text-slate-100 p-6 border border-slate-800 shadow-xl font-mono text-xs">
  <div class="text-center font-bold text-teal-400 text-xs tracking-wider uppercase mb-6">Authentic Composing Telemetry Waveform</div>
  
  <div class="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-4">
    <div class="flex justify-between items-center text-[11px] text-slate-400">
      <span class="text-emerald-400 font-bold">Profile A: Jagged WPM Velocity Curve with P-Bursts &amp; R-Bursts</span>
      <span class="text-teal-400">High Biometric Variance</span>
    </div>

    <!-- Stylized Waveform Graphic -->
    <div class="relative h-32 w-full bg-slate-950 rounded-lg p-3 border border-slate-800 flex items-end justify-between gap-1 overflow-hidden">
      <!-- Grid lines -->
      <div class="absolute inset-0 flex flex-col justify-between p-2 opacity-10 pointer-events-none">
        <div class="border-b border-white w-full"></div>
        <div class="border-b border-white w-full"></div>
        <div class="border-b border-white w-full"></div>
        <div class="border-b border-white w-full"></div>
      </div>

      <!-- Bars simulating authentic waveform -->
      <div class="w-3 bg-emerald-500/80 rounded-t h-[40%]" title="00:30 - Thesis Start (35 WPM)"></div>
      <div class="w-3 bg-emerald-500 rounded-t h-[75%]" title="01:15 - P-Burst 1 (68 WPM)"></div>
      <div class="w-3 bg-emerald-500 rounded-t h-[90%]" title="01:45 - P-Burst Peak (85 WPM)"></div>
      <div class="w-3 bg-emerald-500/60 rounded-t h-[45%]" title="02:10 - Deceleration"></div>
      <div class="w-8 bg-amber-500/20 border-b-2 border-amber-400 h-[8%]" title="02:30–03:15 - Cognitive Planning Pause (6.8s)"></div>
      <div class="w-3 bg-rose-500 rounded-t h-[30%]" title="03:20 - R-Burst: Deleted 48 chars"></div>
      <div class="w-3 bg-rose-500 rounded-t h-[60%]" title="03:45 - R-Burst: Sentence Restructuring"></div>
      <div class="w-3 bg-emerald-500 rounded-t h-[55%]" title="04:10 - New Clause"></div>
      <div class="w-3 bg-emerald-500 rounded-t h-[80%]" title="04:40 - P-Burst 2 (74 WPM)"></div>
      <div class="w-10 bg-amber-500/20 border-b-2 border-amber-400 h-[6%]" title="05:10–06:20 - Paragraph Boundary Pause (14.2s)"></div>
      <div class="w-3 bg-emerald-500 rounded-t h-[65%]" title="06:30 - Body Para 1 (58 WPM)"></div>
      <div class="w-3 bg-emerald-500 rounded-t h-[95%]" title="07:00 - Synthesis Burst (92 WPM)"></div>
      <div class="w-3 bg-emerald-500/70 rounded-t h-[50%]" title="07:30 - Evidence Quote"></div>
      <div class="w-3 bg-rose-500 rounded-t h-[40%]" title="08:00 - R-Burst: Thesis Realignment"></div>
      <div class="w-8 bg-amber-500/20 border-b-2 border-amber-400 h-[8%]" title="08:20–09:00 - Source Verification Pause"></div>
      <div class="w-3 bg-emerald-500 rounded-t h-[70%]" title="09:15 - Concluding Synthesis (64 WPM)"></div>
    </div>

    <div class="flex flex-wrap items-center justify-between text-[10px] text-slate-400 gap-2 pt-2 border-t border-slate-800">
      <span class="flex items-center gap-1.5"><span class="h-2 w-2 rounded-full bg-emerald-500"></span> P-Burst (Productive Typing)</span>
      <span class="flex items-center gap-1.5"><span class="h-2 w-2 rounded-full bg-amber-400"></span> Cognitive Planning Pause (2–15s)</span>
      <span class="flex items-center gap-1.5"><span class="h-2 w-2 rounded-full bg-rose-500"></span> R-Burst (Deletions &amp; Reorganization)</span>
    </div>
  </div>
</div>

<h4>Production Bursts (P-Bursts)</h4>
<p>A <strong>Production Burst</strong> (or P-burst) is an uninterrupted sequence of keystrokes produced between two cognitive pauses.</p>
<ul>
  <li><strong>Burst Length:</strong> In authentic student writing, P-bursts are relatively short, typically ranging from <strong>4 to 18 words</strong> (or 20 to 90 characters).</li>
  <li><strong>Syntactic Boundary Alignment:</strong> P-bursts end naturally at syntactic and conceptual boundaries—such as the end of a clause, before a complex prepositional phrase, or at a paragraph transition.</li>
  <li><strong>Planning Pauses:</strong> Between P-bursts, the student enters a reflective pause of <strong>2.0 to 15.0+ seconds</strong> to plan the next syntactic unit.</li>
</ul>

<h4>Revision Bursts (R-Bursts)</h4>
<p>A <strong>Revision Burst</strong> (or R-burst) occurs when a student actively modifies, deletes, reorganizes, or restructures previously generated text.</p>
<ul>
  <li><strong>Non-Linear Cursor Navigation:</strong> The student leaves the current line of typing, navigates backward via mouse clicks or arrow keys to an earlier sentence or paragraph, and makes structural alterations.</li>
  <li><strong>Conceptual &amp; Syntactic Restructuring:</strong> R-bursts are not limited to single-letter typo corrections. They involve deleting whole phrases, splitting run-on sentences, swapping adjectives for precise analytical terms, and rewriting topic sentences.</li>
  <li><strong>Friction Metrics:</strong> In authentic student drafting, the <strong>Deletion-to-Insertion Ratio (DIR)</strong> typically ranges between <strong>12% and 30%</strong>. For every 1,000 characters present in the final submission, an honest student typically generates 1,150 to 1,450 total key actions due to active drafting and editing.</li>
</ul>

<hr class="my-6 border-border" />

<h3>The Anatomy of Optical Transcription / Retyping</h3>

<p>
  When a student transcribes text from a secondary screen, the entire cognitive architecture of planning, translating, and reviewing is bypassed. The task is reduced to a purely mechanical <strong>eye-hand transcription loop</strong>:
</p>

<!-- Retyping Motor Loop Diagram -->
<div class="my-6 p-4 rounded-xl bg-slate-900 text-teal-300 font-mono text-xs text-center border border-slate-800 shadow-inner overflow-x-auto">
  Optical Saccade (Phone / 2nd Screen) &rarr; Phonological Buffer (4–7 words) &rarr; Motor Typing Burst &rarr; Next Chunk Saccade (0.8–1.8s)
</div>

<p>Because the LLM has already handled the vocabulary, syntax, structural coherence, and argumentative logic:</p>

<ol>
  <li><strong>Absence of Conceptual Planning Pauses:</strong> The student does not pause for 5 to 15 seconds at complex sentence boundaries or paragraph transitions because they do not need to construct the argument. The only pauses observed are brief, uniform <strong>eye-saccade pauses (0.8 to 1.8 seconds)</strong> as their eyes shift from the laptop screen back to their phone to read the next chunk.</li>
  <li><strong>Metronomic Velocity &amp; Narrow IKI Variance:</strong> Keystrokes are entered with mechanical regularity. The Inter-Key Intervals (IKIs) show almost zero variation between simple transition words and intricate disciplinary arguments.</li>
  <li><strong>Monotonic Linear Growth (0 &rarr; N):</strong> Character insertion moves strictly forward from index 0 to index N. The cursor never navigates backward to restructure an earlier paragraph or rethink a supporting claim.</li>
  <li><strong>Typo-Only Superficial Corrections:</strong> When deletions occur, they are exclusively immediate single-character backspaces (1–3 strokes) triggered by a physical slip of the finger (e.g., typing <code>teh</code> instead of <code>the</code>), followed immediately by resumed linear typing. The Deletion-to-Insertion Ratio drops to <strong>&lt; 3%</strong>.</li>
</ol>

<hr class="my-8 border-border" />

<h2>3. Keystroke Telemetry Metrics: Mathematical Modeling</h2>

<p>
  Writing process telemetry converts continuous keyboard and mouse interactions into structured, millisecond-accurate event data. Every interaction is recorded as a discrete event tuple:
</p>

<div class="my-4 rounded-xl bg-slate-900 text-slate-100 p-4 font-mono text-xs overflow-x-auto border border-slate-800">
  <span class="text-teal-400">e<sub>i</sub></span> &equals; &lang; k<sub>i</sub>, t<sub>down, i</sub>, t<sub>up, i</sub>, c<sub>i</sub>, a<sub>i</sub> &rang;
</div>

<p>Where:</p>
<ul>
  <li><code>k<sub>i</sub></code> represents the key code or input identifier (e.g., character, <code>Backspace</code>, <code>ArrowUp</code>, <code>Enter</code>).</li>
  <li><code>t<sub>down, i</sub></code> and <code>t<sub>up, i</sub></code> represent millisecond timestamps for key press and key release.</li>
  <li><code>c<sub>i</sub></code> is the exact integer cursor index in the document text buffer.</li>
  <li><code>a<sub>i</sub></code> represents the mutation category: character insertion (<em>I</em>), character deletion (<em>D</em>), text selection (<em>S</em>), navigation (<em>N</em>), or paste (<em>P</em>).</li>
</ul>

<p>From this raw stream, four core mathematical metrics separate authentic composition from mechanical transcription:</p>

<!-- 4 Core Metrics Grid -->
<div class="my-6 grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
  <div class="p-4 rounded-xl bg-card border border-border shadow-sm">
    <div class="font-bold text-foreground text-sm mb-1 text-teal-600 dark:text-teal-400">1. Inter-Key Interval (IKI) Variance</div>
    <p class="text-muted-foreground">Measures typing rhythm fluidity vs metronomic uniformity. Authentic writing produces high standard deviation (&sigma; &gt; 0.70&mu;), whereas copy-typing produces tight Gaussian clustering (&sigma; &lt; 0.28&mu;).</p>
  </div>
  <div class="p-4 rounded-xl bg-card border border-border shadow-sm">
    <div class="font-bold text-foreground text-sm mb-1 text-teal-600 dark:text-teal-400">2. Deletion-to-Insertion Ratio (DIR)</div>
    <p class="text-muted-foreground">Quantifies drafting friction and self-correction volume. Authentic writing ranges from 12% to 32%, whereas optical retyping drops below 3.5% (typos only).</p>
  </div>
  <div class="p-4 rounded-xl bg-card border border-border shadow-sm">
    <div class="font-bold text-foreground text-sm mb-1 text-teal-600 dark:text-teal-400">3. Non-Linear Navigation Rate (NNR)</div>
    <p class="text-muted-foreground">Tracks cursor relocation away from the typing frontier. Authentic composition exhibits high NNR (0.08–0.25) across paragraphs, while transcription is strictly linear (NNR &lt; 0.01).</p>
  </div>
  <div class="p-4 rounded-xl bg-card border border-border shadow-sm">
    <div class="font-bold text-foreground text-sm mb-1 text-teal-600 dark:text-teal-400">4. Boundary Pause Latency Ratio (BPLR)</div>
    <p class="text-muted-foreground">Evaluates pause depth at paragraph and clause thresholds relative to within-word pauses. Authentic BPLR &ge; 3.5; transcription BPLR &approx; 1.0–1.4.</p>
  </div>
</div>

<hr class="my-6 border-border" />

<h3>1. Inter-Key Interval (IKI) Variance and Distribution Skewness</h3>

<p>The Inter-Key Interval is the latency between consecutive keystrokes:</p>

<div class="my-4 rounded-xl bg-slate-900 text-slate-100 p-4 font-mono text-xs overflow-x-auto border border-slate-800">
  <span class="text-teal-400">IKI<sub>i</sub></span> &equals; t<sub>down, i+1</sub> &minus; t<sub>down, i</sub>
</div>

<ul>
  <li><strong>Authentic Drafting:</strong> Characterized by a heavy-tailed, multimodal distribution. High-frequency motor digraphs (e.g., <code>th</code>, <code>in</code>, <code>er</code>) execute rapidly (70 ms &le; IKI &le; 140 ms), while word retrieval transitions (300 ms &le; IKI &le; 800 ms) and syntactic pauses (1,500 ms &le; IKI &le; 8,000+ ms) introduce substantial variance:
    <div class="my-2 font-mono text-teal-600 dark:text-teal-400 font-semibold">&sigma;<sub>IKI</sub> &approx; 0.70 &middot; &mu;<sub>IKI</sub> &emsp;to&emsp; 1.60 &middot; &mu;<sub>IKI</sub></div>
  </li>
  <li><strong>Mechanical Retyping:</strong> Characterized by a tight, unimodal, near-Gaussian distribution centered around the student&apos;s baseline copy-typing speed, with minimal variance:
    <div class="my-2 font-mono text-rose-600 dark:text-rose-400 font-semibold">&sigma;<sub>IKI</sub> &lt; 0.28 &middot; &mu;<sub>IKI</sub></div>
  </li>
</ul>

<hr class="my-6 border-border" />

<h3>2. Deletion-to-Insertion Ratio (DIR)</h3>

<p>The Deletion-to-Insertion Ratio measures the overall drafting friction by comparing deleted characters against inserted characters:</p>

<div class="my-4 rounded-xl bg-slate-900 text-slate-100 p-4 font-mono text-xs overflow-x-auto border border-slate-800">
  <span class="text-teal-400">DIR</span> &equals; [ &sum; |chars deleted in e<sub>i</sub>| / &sum; |chars inserted in e<sub>j</sub>| ] &times; 100%
</div>

<ul>
  <li><strong>Authentic Drafting Benchmark:</strong> <code>DIR &isin; [12%, 32%]</code>. In rigorous analytical essays, students regularly delete full clauses, test alternative topic sentences, and rework phrasing.</li>
  <li><strong>Optical Retyping Benchmark:</strong> <code>DIR &isin; [0.5%, 3.5%]</code>. Deletions consist solely of immediate single-character backspacing to fix motor typos.</li>
</ul>

<hr class="my-6 border-border" />

<h3>3. Non-Linear Navigation Rate (NNR)</h3>

<p>The Non-Linear Navigation Rate calculates the proportion of cursor movements that jump away from the active typing frontier to modify or review preceding sections:</p>

<div class="my-4 rounded-xl bg-slate-900 text-slate-100 p-4 font-mono text-xs overflow-x-auto border border-slate-800">
  <span class="text-teal-400">NNR</span> &equals; [ &sum; Indicator(|c<sub>i</sub> &minus; c<sub>i-1</sub>| &gt; &Delta;<sub>thresh</sub> &and; a<sub>i</sub> &isin; {I, D, S}) ] / N<sub>total mutations</sub>
</div>

<p>Where &Delta;<sub>thresh</sub> &ge; 50 characters.</p>
<ul>
  <li><strong>Authentic Drafting:</strong> High NNR (0.08–0.25). The writer routinely returns to earlier paragraphs to insert transition sentences, align terminology, or add citations.</li>
  <li><strong>Optical Retyping:</strong> Near-zero NNR (&lt; 0.01). The cursor remains anchored exclusively at the end of the text buffer throughout the entire session.</li>
</ul>

<hr class="my-6 border-border" />

<h3>4. Boundary Pause Latency Ratio (BPLR)</h3>

<p>Syntactic boundary pauses reflect the cognitive effort of structuring paragraphs and complex arguments:</p>

<div class="my-4 rounded-xl bg-slate-900 text-slate-100 p-4 font-mono text-xs overflow-x-auto border border-slate-800">
  <span class="text-teal-400">BPLR</span> &equals; [ Mean Pause Time(paragraph &amp; clause boundaries) ] / [ Mean Pause Time(intra-word &amp; intra-phrase boundaries) ]
</div>

<ul>
  <li><strong>Authentic Drafting:</strong> <code>BPLR &ge; 3.5</code>. Pauses at paragraph and sentence thresholds are substantially longer than pauses within words or simple noun phrases.</li>
  <li><strong>Optical Retyping:</strong> <code>BPLR &approx; 1.0 – 1.4</code>. Pauses at paragraph boundaries are roughly identical in duration to pauses within sentences, reflecting the steady rhythm of reading short chunks off a second screen.</li>
</ul>

<hr class="my-6 border-border" />

<h3>Waveform Comparison: Jagged Composing vs. Flat Retyping</h3>

<!-- Waveform Comparison Box -->
<div class="my-8 rounded-2xl bg-card border border-border p-6 shadow-sm">
  <div class="text-center font-bold text-foreground text-xs tracking-wider uppercase mb-6">Real-Time WPM Velocity Curve Comparison</div>
  <div class="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs font-mono">
    <!-- Profile A -->
    <div class="rounded-xl bg-muted/40 p-4 border border-border space-y-3">
      <div class="text-emerald-600 dark:text-emerald-400 font-bold flex items-center justify-between">
        <span>Profile A: Authentic Composing</span>
        <span class="text-[10px] px-2 py-0.5 rounded bg-emerald-500/10">High Friction</span>
      </div>
      <p class="text-muted-foreground font-sans text-[11px]">
        Dynamic, jagged peaks (P-bursts) reaching 85 WPM punctuated by deep cognitive valleys (0 WPM pauses of 4–15s) and red downward revision markers (-120 chars).
      </p>
      <div class="h-20 bg-slate-950 rounded-lg p-2 border border-slate-800 flex items-end gap-1.5 overflow-hidden">
        <span class="w-3 bg-emerald-500 h-[50%] rounded-t"></span>
        <span class="w-3 bg-emerald-500 h-[85%] rounded-t"></span>
        <span class="w-5 bg-amber-400/30 h-[10%] border-b border-amber-400"></span>
        <span class="w-3 bg-rose-500 h-[40%] rounded-t"></span>
        <span class="w-3 bg-emerald-500 h-[70%] rounded-t"></span>
        <span class="w-6 bg-amber-400/30 h-[10%] border-b border-amber-400"></span>
        <span class="w-3 bg-emerald-500 h-[90%] rounded-t"></span>
        <span class="w-3 bg-rose-500 h-[30%] rounded-t"></span>
      </div>
      <div class="text-[10px] text-muted-foreground">DIR: 24.2% | &sigma;<sub>IKI</sub>: 540ms | Non-Linear: Yes</div>
    </div>

    <!-- Profile B -->
    <div class="rounded-xl bg-muted/40 p-4 border border-border space-y-3">
      <div class="text-rose-600 dark:text-rose-400 font-bold flex items-center justify-between">
        <span>Profile B: Mechanical Optical Retyping</span>
        <span class="text-[10px] px-2 py-0.5 rounded bg-rose-500/10">Zero Friction</span>
      </div>
      <p class="text-muted-foreground font-sans text-[11px]">
        Completely flat horizontal line hovering steadily at 52 WPM from paragraph 1 to the bibliography, with uniform 1.2s eye-saccade pauses and zero structural cuts.
      </p>
      <div class="h-20 bg-slate-950 rounded-lg p-2 border border-slate-800 flex items-center gap-1 overflow-hidden">
        <div class="w-full h-1.5 bg-rose-500 rounded"></div>
      </div>
      <div class="text-[10px] text-muted-foreground">DIR: 0.6% | &sigma;<sub>IKI</sub>: 74ms | Non-Linear: No</div>
    </div>
  </div>
</div>

<hr class="my-8 border-border" />

<h2>4. Telemetry Comparison Spectrum</h2>

<p>The following matrix compares authentic writing against common evasion and drafting profiles:</p>

<!-- Full Comparative Spectrum Table -->
<div class="my-6 overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
  <div class="overflow-x-auto">
    <table class="w-full text-left text-xs border-collapse">
      <thead>
        <tr class="border-b border-border bg-muted/60 font-semibold text-foreground">
          <th class="p-3.5">Diagnostic Dimension</th>
          <th class="p-3.5">Authentic Student Composition</th>
          <th class="p-3.5">Mechanical Optical Retyping (2nd Screen)</th>
          <th class="p-3.5">Direct External Block Paste</th>
          <th class="p-3.5">Paraphrased / &ldquo;Humanized&rdquo; AI</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-border text-muted-foreground">
        <tr>
          <td class="p-3.5 font-medium text-foreground">Keystroke Velocity Curve</td>
          <td class="p-3.5 text-emerald-600 dark:text-emerald-400 font-semibold">Dynamic, jagged peaks (P-bursts) punctuated by deep cognitive valleys (0 WPM).</td>
          <td class="p-3.5 text-rose-600 dark:text-rose-400 font-semibold">Uniform, flat horizontal line across the entire session (45–65 WPM).</td>
          <td class="p-3.5">Instantaneous vertical spike (&gt;2,000 WPM equivalent).</td>
          <td class="p-3.5">Flat or block profile depending on paste vs retyping method.</td>
        </tr>
        <tr>
          <td class="p-3.5 font-medium text-foreground">IKI Variance (&sigma;<sub>IKI</sub>)</td>
          <td class="p-3.5 text-emerald-600 dark:text-emerald-400 font-semibold">High (&sigma; &gt; 0.75 &middot; &mu;); significant rhythm fluctuations.</td>
          <td class="p-3.5 text-rose-600 dark:text-rose-400 font-semibold">Minimal (&sigma; &lt; 0.28 &middot; &mu;); metronomic, clock-like regularity.</td>
          <td class="p-3.5">Undefined / Null (single event insertion).</td>
          <td class="p-3.5">Minimal if retyped; null if pasted.</td>
        </tr>
        <tr>
          <td class="p-3.5 font-medium text-foreground">Deletion Ratio (DIR)</td>
          <td class="p-3.5 text-emerald-600 dark:text-emerald-400 font-semibold">High (12% – 32%); extensive phrasing experiments and rewrites.</td>
          <td class="p-3.5 text-rose-600 dark:text-rose-400 font-semibold">Extremely low (0.5% – 3.5%); immediate typo corrections only.</td>
          <td class="p-3.5">0% at time of insertion; variable subsequent edits.</td>
          <td class="p-3.5">Low to moderate if student tweaks individual words.</td>
        </tr>
        <tr>
          <td class="p-3.5 font-medium text-foreground">Cursor Navigation Entropy</td>
          <td class="p-3.5 text-emerald-600 dark:text-emerald-400 font-semibold">High; frequent jumps across paragraphs and sections.</td>
          <td class="p-3.5 text-rose-600 dark:text-rose-400 font-semibold">Strictly linear (0 &rarr; N); cursor stays at the text frontier.</td>
          <td class="p-3.5">Instant jump from offset A to offset B.</td>
          <td class="p-3.5">Primarily linear.</td>
        </tr>
        <tr>
          <td class="p-3.5 font-medium text-foreground">Boundary Pause Depth</td>
          <td class="p-3.5 text-emerald-600 dark:text-emerald-400 font-semibold">Deep reflective pauses (3.0s – 25.0s+) at structural shifts.</td>
          <td class="p-3.5 text-rose-600 dark:text-rose-400 font-semibold">Shallow, uniform pauses (0.8s – 1.8s) for eye saccades.</td>
          <td class="p-3.5">Zero elapsed drafting time within the document.</td>
          <td class="p-3.5">Shallow or missing structural pauses.</td>
        </tr>
        <tr>
          <td class="p-3.5 font-medium text-foreground">Clipboard Paste Records</td>
          <td class="p-3.5">Normal occasional quotes or research excerpts (&lt;15% text).</td>
          <td class="p-3.5 text-rose-600 dark:text-rose-400">Zero paste events recorded.</td>
          <td class="p-3.5 text-rose-600 dark:text-rose-400">100% text inserted in single paste operation.</td>
          <td class="p-3.5">Zero if retyped; block log if pasted.</td>
        </tr>
        <tr>
          <td class="p-3.5 font-medium text-foreground">Educator Action</td>
          <td class="p-3.5 font-semibold text-emerald-600 dark:text-emerald-400">Validate authenticity; provide formative rubric feedback.</td>
          <td class="p-3.5 font-semibold text-teal-600 dark:text-teal-400">Review Essay Playback™; conduct supportive inquiry conference.</td>
          <td class="p-3.5 font-semibold text-amber-600 dark:text-amber-400">Inspect preserved clipboard buffer; clarify citation rules.</td>
          <td class="p-3.5 font-semibold text-amber-600 dark:text-amber-400">Check passage-level sliders and playback telemetry.</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<hr class="my-8 border-border" />

<h2>5. Checkmark Plagiarism: Essay Playback™ &amp; Multi-Factor Verification Suite</h2>

<p>
  Checkmark Plagiarism (<a href="/">checkmarkplagiarism.com</a>) was engineered specifically to solve the limitations of opaque, whole-paper percentage scores. Guided by the core principle <strong>&ldquo;Stop guessing, start trusting,&rdquo;</strong> Checkmark provides educators, department chairs, and academic integrity officers with transparent, defensible, multi-dimensional evidence (&ldquo;receipts&rdquo;).
</p>

<!-- Verification Suite Architecture Grid -->
<div class="my-8 rounded-2xl bg-card border border-border p-6 shadow-sm">
  <div class="text-center font-bold text-foreground text-xs tracking-wider uppercase mb-6">Checkmark Plagiarism Multi-Factor Verification Triad</div>
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 text-xs">
    <div class="rounded-xl bg-muted/40 p-4 border border-border flex flex-col justify-between">
      <div>
        <div class="font-bold text-foreground text-sm mb-1 text-teal-600 dark:text-teal-400">1. Essay Playback™</div>
        <ul class="space-y-1.5 text-muted-foreground list-disc pl-4 mt-2">
          <li>1x–8x scrubbable video replay</li>
          <li>Synchronized velocity telemetry curve</li>
          <li>Transcription cadence alerts</li>
          <li>Native Canvas &amp; Buzz LMS player</li>
        </ul>
      </div>
      <div class="mt-3 pt-2 border-t border-border text-[11px] text-teal-600 dark:text-teal-400 font-medium">
        <a href="/services/writing-playback">Explore Essay Playback &rarr;</a>
      </div>
    </div>

    <div class="rounded-xl bg-muted/40 p-4 border border-border flex flex-col justify-between">
      <div>
        <div class="font-bold text-foreground text-sm mb-1 text-teal-600 dark:text-teal-400">2. Paste Buffer Tracker</div>
        <ul class="space-y-1.5 text-muted-foreground list-disc pl-4 mt-2">
          <li>100% clipboard history stored</li>
          <li>Preserves raw text after rewrites</li>
          <li>Direct jump-to-playback timecodes</li>
          <li>Uncited quote differentiation</li>
        </ul>
      </div>
      <div class="mt-3 pt-2 border-t border-border text-[11px] text-teal-600 dark:text-teal-400 font-medium">
        <a href="/services/plagiarism-detection">Explore Paste Tracking &rarr;</a>
      </div>
    </div>

    <div class="rounded-xl bg-muted/40 p-4 border border-border flex flex-col justify-between">
      <div>
        <div class="font-bold text-foreground text-sm mb-1 text-teal-600 dark:text-teal-400">3. Passage-Level AI</div>
        <ul class="space-y-1.5 text-muted-foreground list-disc pl-4 mt-2">
          <li>Sentence-by-sentence underlines</li>
          <li>Calibrated confidence sliders</li>
          <li>Short text guardrails (&lt;150w &equals; N/A)</li>
          <li>Confidential educator-only flags</li>
        </ul>
      </div>
      <div class="mt-3 pt-2 border-t border-border text-[11px] text-teal-600 dark:text-teal-400 font-medium">
        <a href="/services/ai-detection">Explore AI Detection &rarr;</a>
      </div>
    </div>

    <div class="rounded-xl bg-muted/40 p-4 border border-border flex flex-col justify-between">
      <div>
        <div class="font-bold text-foreground text-sm mb-1 text-teal-600 dark:text-teal-400">4. Rubric Autograder</div>
        <ul class="space-y-1.5 text-muted-foreground list-disc pl-4 mt-2">
          <li>Quote-anchored justifications</li>
          <li>Teacher-in-the-loop approvals</li>
          <li>Custom rubric alignment</li>
          <li>Direct Canvas &amp; Buzz LMS passback</li>
        </ul>
      </div>
      <div class="mt-3 pt-2 border-t border-border text-[11px] text-teal-600 dark:text-teal-400 font-medium">
        <a href="/services/autograder">Explore Rubric Autograder &rarr;</a>
      </div>
    </div>
  </div>
</div>

<h3>1. Patent-Pending Essay Playback™ Suite</h3>
<p>The centerpiece of Checkmark&apos;s writing process verification is <a href="/services/writing-playback"><strong>Essay Playback™</strong></a>, an interactive tool that reconstructs the entire drafting session keystroke by keystroke:</p>
<ul>
  <li><strong>1x to 8x Scrubbable Chronological Video Player:</strong> Educators can watch the document develop over time. Teachers can scrub through hours of drafting in minutes, watching where the student paused to think, where they struggled with a thesis statement, and how their ideas evolved.</li>
  <li><strong>Burst-Velocity Telemetry Overlay:</strong> Synchronized directly beneath the playback window is a real-time velocity curve. Spikes represent rapid P-bursts; dips represent reflective planning pauses; red downward markers highlight deletion events.</li>
  <li><strong>Transcription Detection Indicators:</strong> When a submission exhibits the statistical profile of optical transcription—low IKI variance (&sigma; &lt; 0.28&mu;), continuous linear insertion, and a near-zero deletion ratio—Checkmark surfaces a private <strong>Transcription Cadence Alert</strong> for the educator.</li>
  <li><strong>Native Ecosystem Integration:</strong> Essay Playback™ captures authentic revision telemetry directly across Google Docs, Microsoft Word (via Checkmark integrations), and embedded LMS editors in <a href="/services/integrations/canvas-lms">Canvas LMS</a> and Buzz LMS.</li>
</ul>

<h3>2. External Paste Buffer Tracking with Complete Text Preservation</h3>
<p>When students paste text into a document, traditional tools often lose the original pasted string if the student subsequently edits, rewrites, or paraphrases the text to cover their tracks.</p>
<ul>
  <li><strong>100% Text Buffer Preservation:</strong> Checkmark captures and permanently preserves the exact text copied into the clipboard at the precise millisecond of insertion.</li>
  <li><strong>Post-Paste Edit Tracking:</strong> Even if a student pastes 800 words and spends the next 40 minutes swapping words and altering sentence structures, Checkmark retains the original raw paste string and displays it side-by-side with the final version.</li>
  <li><strong>Jump-to-Playback Navigation:</strong> Clicking any paste alert in the report timeline immediately scrubs the Essay Playback™ player to the exact moment the paste occurred.</li>
</ul>

<h3>3. Multi-Factor AI Detection with Honest Guardrails</h3>
<p>Checkmark rejects opaque, single-number whole-document percentages that lead to false accusations:</p>
<ul>
  <li><strong>Passage-Level Granularity:</strong> Rather than labeling an entire essay &ldquo;65% AI,&rdquo; Checkmark highlights specific sentences and paragraphs directly within the text buffer.</li>
  <li><strong>Sidebar Evidence Cards &amp; Confidence Sliders:</strong> Every highlighted passage links to an evidence card showing a calibrated confidence slider (distinguishing typical human writing variation from typical AI syntactic predictability/perplexity).</li>
  <li><strong>Honest Guardrails on Short Text:</strong> For text fragments under ~150 words, Checkmark displays <code>N/A</code> rather than generating unreliable guesses on statistically insufficient sample sizes.</li>
  <li><strong>Educator-Only Flag Statuses:</strong> Flag statuses (<em>Flagged</em>, <em>Resolved</em>, <em>Not Flagged</em>) remain strictly confidential to educators, preventing premature or automated disciplinary measures.</li>
</ul>

<h3>4. Side-by-Side Defensible Plagiarism Matching</h3>
<ul>
  <li><strong>Live Web &amp; Academic Indexing:</strong> Compares student writing against billions of live web pages, academic journals, open-access databases, and institutional repositories.</li>
  <li><strong>Dedicated Uncited Source Differentiation:</strong> Separates intentional verbatim plagiarism from uncredited patchwriting and citation formatting errors, allowing teachers to provide targeted citation instruction.</li>
  <li><strong>Internal Peer Match Network:</strong> Identifies unapproved text sharing between students in the same class, department, or school district repository without exposing student submissions to public LLM datasets.</li>
  <li><strong>Two-Way Linked Evidence Navigation:</strong> Clicking any highlighted source passage in the essay instantly brings up the matching source excerpt with active links in the sidebar, and vice versa.</li>
</ul>

<h3>5. AI Autograder &amp; Rubric-Based Feedback</h3>
<ul>
  <li><strong>Teacher-in-the-Loop Grading:</strong> Checkmark&apos;s autograder evaluates submissions against custom rubrics, generating point suggestions and written justifications tied directly to specific quotes in the student&apos;s text.</li>
  <li><strong>Editable Drafts:</strong> All AI-suggested marks remain provisional drafts until the instructor reviews, edits, and finalizes them.</li>
  <li><strong>Direct LMS Grade Passback:</strong> With a single click, finalized scores, criterion breakdowns, and qualitative feedback push directly into the <a href="/services/integrations/canvas-lms">Canvas LMS</a> or Buzz LMS gradebook.</li>
</ul>

<h3>6. Protecting and Exonerating Honest Students</h3>
<p>
  The most vital pedagogical benefit of writing telemetry is protecting honest students from false accusations. Non-native English speakers (ESL/ELL) and students with structured, formal writing styles are disproportionately misclassified by generic static AI detectors.
</p>

<p>
  When an ESL student is flagged by an external static detector because their vocabulary is formal and predictable, <strong>Checkmark&apos;s Essay Playback™ serves as their definitive defense</strong>. The educator opens Playback and observes:
</p>
<ul>
  <li>45 minutes of genuine drafting effort.</li>
  <li>Multiple 10-second pauses while the student consulted a dictionary or wrestled with complex syntax.</li>
  <li>Active revision bursts showing recursive deletions and rewritten clauses.</li>
</ul>

<p>
  The biometric process evidence completely exonerates the student, turning a potentially damaging disciplinary conflict into a moment of trust and validation.
</p>

<!-- Interactive Essay Playback Mockup Card -->
<div class="my-8 rounded-2xl bg-slate-950 text-slate-100 p-6 border border-slate-800 shadow-xl font-mono text-xs">
  <div class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 border-b border-slate-800 pb-4 mb-4">
    <div class="flex items-center gap-2.5">
      <span class="h-3 w-3 rounded-full bg-rose-500 animate-pulse"></span>
      <span class="font-bold text-sm text-white tracking-tight">Checkmark Essay Playback™ Investigation Suite</span>
    </div>
    <div class="flex items-center gap-2 text-[11px] text-slate-400">
      <span class="px-2.5 py-1 rounded bg-slate-900 border border-slate-800 text-teal-400 font-semibold">Speed: 4x &blacktriangledown;</span>
      <span class="px-2.5 py-1 rounded bg-slate-900 border border-slate-800">18:42 / 28:30</span>
    </div>
  </div>

  <!-- Scrub Bar -->
  <div class="space-y-2 mb-5">
    <div class="w-full bg-slate-800 rounded-full h-3 relative overflow-hidden">
      <div class="bg-gradient-to-r from-teal-500 via-amber-500 to-rose-500 h-full w-[68%] rounded-full"></div>
      <div class="absolute top-0 left-[21%] bottom-0 w-1 bg-white/80" title="Cadence Anomaly Detected"></div>
      <div class="absolute top-0 left-[54%] bottom-0 w-1 bg-white/80" title="Zero Clause Pause Segment"></div>
    </div>
    <div class="flex justify-between text-[10px] text-slate-400">
      <span>00:00 [Start]</span>
      <span>06:00 [82 WPM Cadence]</span>
      <span>12:00 [Zero Pauses]</span>
      <span>18:00 [Monotonic]</span>
      <span>28:30 [Submit]</span>
    </div>
  </div>

  <!-- Anomaly Alert Banner -->
  <div class="mb-5 p-3 rounded-xl bg-rose-950/60 border border-rose-500/40 text-rose-200 flex items-center justify-between gap-2">
    <div class="flex items-center gap-2">
      <span class="text-rose-400 text-sm">&warning;</span>
      <span class="font-semibold text-xs">CADENCE ANOMALY DETECTED: Transcription Signature (98.4% Confidence)</span>
    </div>
    <span class="text-[10px] px-2 py-0.5 rounded bg-rose-500/20 text-rose-300 border border-rose-500/30">Educator View</span>
  </div>

  <!-- Telemetry Metrics Breakdown Bar -->
  <div class="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-5 text-[11px]">
    <div class="p-2.5 rounded-lg bg-slate-900 border border-slate-800">
      <span class="text-slate-400 block text-[10px]">Net Composition Rate</span>
      <span class="text-rose-400 font-bold text-sm">78.4 WPM</span>
      <span class="text-[9px] text-slate-500 block">(Top 0.5% Speed)</span>
    </div>
    <div class="p-2.5 rounded-lg bg-slate-900 border border-slate-800">
      <span class="text-slate-400 block text-[10px]">IKI Variance (&sigma;)</span>
      <span class="text-rose-400 font-bold text-sm">84 ms</span>
      <span class="text-[9px] text-slate-500 block">(Metronomic Cadence)</span>
    </div>
    <div class="p-2.5 rounded-lg bg-slate-900 border border-slate-800">
      <span class="text-slate-400 block text-[10px]">Deletion Ratio (DIR)</span>
      <span class="text-rose-400 font-bold text-sm">0.8%</span>
      <span class="text-[9px] text-slate-500 block">(Zero Clause Cuts)</span>
    </div>
    <div class="p-2.5 rounded-lg bg-slate-900 border border-slate-800">
      <span class="text-slate-400 block text-[10px]">External Pastes</span>
      <span class="text-emerald-400 font-bold text-sm">0 Logged</span>
      <span class="text-[9px] text-slate-500 block">(Manual Retype)</span>
    </div>
  </div>

  <!-- Triangulated Evidence Panels -->
  <div class="grid grid-cols-1 md:grid-cols-3 gap-3 text-[11px]">
    <div class="p-3 rounded-lg bg-slate-900 border border-slate-800">
      <div class="text-teal-400 font-semibold mb-1">1. Passage-Level AI Card</div>
      <p class="text-slate-300 text-[10px] leading-relaxed mb-2">&ldquo;Furthermore, the sociopolitical ramifications...&rdquo;</p>
      <div class="flex items-center justify-between text-[10px] text-slate-400 pt-2 border-t border-slate-800">
        <span>Typical AI Pattern</span>
        <span class="text-amber-300 font-bold">96% Conf</span>
      </div>
    </div>

    <div class="p-3 rounded-lg bg-slate-900 border border-slate-800">
      <div class="text-teal-400 font-semibold mb-1">2. Paste Buffer Monitor</div>
      <p class="text-slate-300 text-[10px] leading-relaxed mb-2">No external clipboard paste events registered during 28-min session.</p>
      <div class="flex items-center justify-between text-[10px] text-slate-400 pt-2 border-t border-slate-800">
        <span>Status</span>
        <span class="text-rose-300 font-bold">Optical Retype</span>
      </div>
    </div>

    <div class="p-3 rounded-lg bg-slate-900 border border-slate-800">
      <div class="text-teal-400 font-semibold mb-1">3. Rubric Autograder</div>
      <p class="text-slate-300 text-[10px] leading-relaxed mb-2">Thesis demonstrates advanced vocabulary without drafting hesitation.</p>
      <div class="flex items-center justify-between text-[10px] text-slate-400 pt-2 border-t border-slate-800">
        <span>Flag Status</span>
        <span class="text-rose-400 font-bold">Review Needed</span>
      </div>
    </div>
  </div>
</div>

<hr class="my-8 border-border" />

<h2>6. Real-World Classroom Case Studies</h2>

<p>The following case studies illustrate how writing telemetry functions across secondary and higher education environments.</p>

<!-- Case Studies Grid -->
<div class="my-8 grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
  <!-- Case 1 -->
  <div class="rounded-2xl bg-card border border-border p-5 shadow-sm flex flex-col justify-between">
    <div>
      <div class="flex items-center justify-between mb-2">
        <span class="px-2 py-0.5 rounded bg-teal-500/10 text-teal-700 dark:text-teal-400 font-bold text-[10px]">Case 1 &bull; AP Lang</span>
        <span class="text-emerald-600 dark:text-emerald-400 font-bold">Exonerated</span>
      </div>
      <h3 class="text-sm font-bold text-foreground mb-2 pt-0">The Thesis Struggle</h3>
      <ul class="space-y-2 text-muted-foreground list-disc pl-4">
        <li><strong>Prompt:</strong> Rhetorical Analysis of Florence Kelley (950 words).</li>
        <li><strong>External Static Flag:</strong> 62% AI Score due to clean syntactic structure.</li>
        <li><strong>Checkmark Telemetry:</strong> 58 min session, &sigma;<sub>IKI</sub> &equals; 1.18&mu;, DIR &equals; 24.2%.</li>
        <li><strong>Playback Evidence:</strong> Student spent 7 minutes drafting 3 thesis variations, deleting 38 words, and returning at min 44 to refine claim.</li>
      </ul>
    </div>
    <div class="mt-4 pt-3 border-t border-border text-[11px] text-emerald-600 dark:text-emerald-400 font-semibold">
      Outcome: Proven authentic authorship; teacher conducted constructive feedback conference.
    </div>
  </div>

  <!-- Case 2 -->
  <div class="rounded-2xl bg-card border border-border p-5 shadow-sm flex flex-col justify-between">
    <div>
      <div class="flex items-center justify-between mb-2">
        <span class="px-2 py-0.5 rounded bg-teal-500/10 text-teal-700 dark:text-teal-400 font-bold text-[10px]">Case 2 &bull; College Comp</span>
        <span class="text-teal-600 dark:text-teal-400 font-bold">Formative Coaching</span>
      </div>
      <h3 class="text-sm font-bold text-foreground mb-2 pt-0">Cold War Historiography</h3>
      <ul class="space-y-2 text-muted-foreground list-disc pl-4">
        <li><strong>Prompt:</strong> Multi-source foreign policy essay (1,800 words).</li>
        <li><strong>Dilemma:</strong> TA suspected advanced periodic sentences were generated.</li>
        <li><strong>Checkmark Telemetry:</strong> 2h 15m session, 45s–4m research pauses at paragraph thresholds.</li>
        <li><strong>Paste Buffer:</strong> 3 primary source quotes pasted directly; uncited source alert triggered.</li>
      </ul>
    </div>
    <div class="mt-4 pt-3 border-t border-border text-[11px] text-teal-600 dark:text-teal-400 font-semibold">
      Outcome: Validated organic research effort; instructor coached student on block quote citations.
    </div>
  </div>

  <!-- Case 3 -->
  <div class="rounded-2xl bg-card border border-border p-5 shadow-sm flex flex-col justify-between">
    <div>
      <div class="flex items-center justify-between mb-2">
        <span class="px-2 py-0.5 rounded bg-rose-500/10 text-rose-600 dark:text-rose-400 font-bold text-[10px]">Case 3 &bull; Higher Ed</span>
        <span class="text-rose-600 dark:text-rose-400 font-bold">Second-Screen Catch</span>
      </div>
      <h3 class="text-sm font-bold text-foreground mb-2 pt-0">Comparative Politics</h3>
      <ul class="space-y-2 text-muted-foreground list-disc pl-4">
        <li><strong>Prompt:</strong> Democratic backsliding paper (1,200 words).</li>
        <li><strong>Static Flag:</strong> 18% (evaded via humanizer prompt).</li>
        <li><strong>Checkmark Telemetry:</strong> 26 min session, flat 51.4 WPM curve, DIR &equals; 0.6%, NNR &equals; 0.00.</li>
        <li><strong>Playback Finding:</strong> Metronomic copy-typing from phone; 0 planning pauses.</li>
      </ul>
    </div>
    <div class="mt-4 pt-3 border-t border-border text-[11px] text-rose-600 dark:text-rose-400 font-semibold">
      Outcome: Student admitted phone transcription during Playback conference; completed restorative rewrite.
    </div>
  </div>
</div>

<hr class="my-8 border-border" />

<h2>7. 4-Phase Restorative Educator Verification Protocol</h2>

<p>
  When an educator observes suspicious telemetry or an automated transcription indicator, conversations should follow a supportive, pedagogical protocol designed to foster reflection rather than confrontation.
</p>

<!-- 4-Phase Protocol Workflow Diagram -->
<div class="my-8 rounded-2xl bg-slate-900 text-slate-100 p-6 border border-slate-800 shadow-md">
  <div class="text-center font-bold text-teal-400 text-xs tracking-wider uppercase mb-6">The 4-Phase Restorative Verification Protocol</div>
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 text-xs">
    <div class="bg-slate-800/90 rounded-xl p-4 border border-slate-700">
      <div class="text-teal-300 font-bold mb-2">Phase 1: Silent Audit</div>
      <ul class="space-y-1.5 text-slate-300 text-[11px] list-disc pl-4">
        <li>Review Essay Playback™ at 4x speed</li>
        <li>Check IKI variance (&sigma;) and DIR friction</li>
        <li>Inspect paste buffers &amp; passage AI cards</li>
      </ul>
    </div>

    <div class="bg-slate-800/90 rounded-xl p-4 border border-slate-700">
      <div class="text-teal-300 font-bold mb-2">Phase 2: Pre-Conference</div>
      <ul class="space-y-1.5 text-slate-300 text-[11px] list-disc pl-4">
        <li>Select 2–3 key timestamps</li>
        <li>Formulate open-ended questions</li>
        <li>Focus strictly on the writing process</li>
      </ul>
    </div>

    <div class="bg-slate-800/90 rounded-xl p-4 border border-slate-700">
      <div class="text-teal-300 font-bold mb-2">Phase 3: Restorative Review</div>
      <ul class="space-y-1.5 text-slate-300 text-[11px] list-disc pl-4">
        <li>Open Playback on shared screen</li>
        <li>&ldquo;Walk me through your thinking here&rdquo;</li>
        <li>Student explains drafting decisions</li>
      </ul>
    </div>

    <div class="bg-slate-800/90 rounded-xl p-4 border border-slate-700">
      <div class="text-teal-300 font-bold mb-2">Phase 4: Resolution</div>
      <ul class="space-y-1.5 text-slate-300 text-[11px] list-disc pl-4">
        <li>Supervised in-class rewrite if copied</li>
        <li>Metacognitive 200-word reflection</li>
        <li>Update private flag in dashboard</li>
      </ul>
    </div>
  </div>
</div>

<h3>Collaborative Playback Review (Conferencing Script)</h3>

<p>Conduct the conference using a screen-share or shared monitor:</p>

<blockquote class="my-4 border-l-4 border-teal-500 pl-4 italic text-muted-foreground text-sm">
  <strong>Educator:</strong> &ldquo;Hi Alex, thanks for meeting with me today. I&apos;ve been reading through your essay on democratic institutions, and you have some really interesting arguments here. In our class, I like to look at the writing process alongside the final draft so I can see how your ideas develop over time.<br /><br />
  I want to pull up our Checkmark Essay Playback viewer together. Let&apos;s look at this section in paragraph 2 where you introduce the concept of institutional decay. Can you walk me through how you decided on this specific framing and how you developed this argument?&rdquo;
</blockquote>

<h4>Scenario A: The Student Authored the Paper</h4>
<blockquote class="my-4 border-l-4 border-emerald-500 pl-4 italic text-muted-foreground text-sm">
  <strong>Student:</strong> &ldquo;Yeah! I initially started by talking about electoral systems, but as I was typing, I realized that judicial independence was a much stronger point for this prompt. You can see where I paused for a couple of minutes to pull up the Levitsky article from our syllabus, and then I rewrote that transition.&rdquo;<br /><br />
  <strong>Educator:</strong> &ldquo;That makes complete sense—I can see your revision right here on the timeline where you updated that claim. Excellent work on that transition.&rdquo;
</blockquote>

<h4>Scenario B: The Student Transcribed from a Second Screen</h4>
<blockquote class="my-4 border-l-4 border-rose-500 pl-4 italic text-muted-foreground text-sm">
  <strong>Educator:</strong> &ldquo;Looking at this section, I notice that all 450 words of this theoretical overview were typed in a single continuous 7-minute burst without any pauses, outline notes, or phrasing adjustments. That&apos;s very unusual for a complex topic like this. Can you tell me what resources you were looking at while typing this paragraph?&rdquo;<br /><br />
  <strong>Student:</strong> <em>[Hesitates]</em> &ldquo;Well... I had some notes on my phone.&rdquo;<br /><br />
  <strong>Educator:</strong> &ldquo;Were those notes you wrote yourself, or did you generate an answer using an AI tool on your phone and type it in?&rdquo;<br /><br />
  <strong>Student:</strong> &ldquo;I was running out of time before the midnight deadline, so I asked ChatGPT to explain the concept and I typed it out from my phone screen.&rdquo;
</blockquote>

<hr class="my-8 border-border" />

<h2>8. Departmental AI &amp; Writing Policy Template</h2>

<p>Department chairs and curriculum coordinators can adapt the following boilerplate policy for inclusion in course syllabi and faculty handbooks:</p>

<div class="my-6 rounded-2xl bg-card border border-border p-6 shadow-sm text-xs font-mono space-y-4">
  <div class="text-foreground font-bold text-sm uppercase tracking-wide">Academic Integrity &amp; Writing Process Policy: Authentic Authorship vs. Transcription</div>
  
  <p class="text-muted-foreground font-sans text-xs leading-relaxed">
    Our department values the writing process as an essential medium for critical thinking, analysis, and personal voice. Clear writing reflects clear thinking, and the productive struggle of drafting, revising, and refining arguments is fundamental to your intellectual development.
  </p>

  <div class="p-3.5 rounded-xl bg-muted/40 border border-border text-foreground font-sans text-xs space-y-2">
    <div class="font-bold text-teal-600 dark:text-teal-400">1. Permitted vs. Unauthorized AI Collaboration</div>
    <ul class="space-y-1.5 list-disc pl-4 text-muted-foreground">
      <li><strong>Authorized Uses (Permitted with Citation):</strong> Using AI tools for initial brainstorming, outlining alternative perspectives, or checking grammar rules is permitted provided all prompts and AI-assisted ideation are documented in an appendix.</li>
      <li><strong>Unauthorized Authorship Fraud (Prohibited):</strong> Submitting text generated by an external Large Language Model as your own work—whether through direct copying and pasting, running text through paraphrasing/humanizing tools, or manually retyping generated content from a secondary screen, phone, or tablet—constitutes academic dishonesty.</li>
    </ul>
  </div>

  <div class="p-3.5 rounded-xl bg-muted/40 border border-border text-foreground font-sans text-xs space-y-2">
    <div class="font-bold text-teal-600 dark:text-teal-400">2. Writing Process Telemetry &amp; Verification</div>
    <p class="text-muted-foreground">
      To ensure fair assessment and protect students from false accusations, this course uses <strong>Checkmark Plagiarism</strong> and <strong>Essay Playback™</strong>. Submissions are evaluated using multi-factor evidence, including passage-level analysis, side-by-side source matching, and timestamped drafting process telemetry.
    </p>
  </div>

  <div class="p-3.5 rounded-xl bg-muted/40 border border-border text-foreground font-sans text-xs space-y-2">
    <div class="font-bold text-teal-600 dark:text-teal-400">3. Protection for Honest Writers</div>
    <p class="text-muted-foreground">
      Your authentic drafting history—including typing rhythms, reflective planning pauses, and sentence-level revisions—serves as your permanent proof of authorship. In the event of any question regarding a submission, students and faculty will review the Essay Playback™ record together in a supportive, transparent conference.
    </p>
  </div>
</div>

<hr class="my-8 border-border" />

<h2>9. Frequently Asked Questions (FAQs)</h2>

<div class="my-6 space-y-4 text-xs">
  <!-- FAQ 1 -->
  <div class="p-5 rounded-2xl bg-card border border-border shadow-sm space-y-2">
    <h3 class="text-sm font-bold text-foreground pt-0">1. How does Checkmark detect manual retyping if no paste event occurred?</h3>
    <p class="text-muted-foreground leading-relaxed">
      While standard clipboard listeners only register <code>Ctrl+V</code> or right-click paste events, Checkmark&apos;s <strong><a href="/services/writing-playback" class="text-teal-600 dark:text-teal-400 underline font-semibold">Essay Playback™</a></strong> analyzes the continuous biomechanical telemetry of the typing session. Optical transcription leaves an unmistakable signature: a flat, metronomic keystroke velocity curve (45–65 WPM), near-zero Inter-Key Interval variance (&sigma; &lt; 0.28&mu;), strictly linear progression (0 &rarr; N), and a near-zero Deletion-to-Insertion Ratio (&lt;3%). When these metrics align, Checkmark generates a private <em>Transcription Cadence Alert</em> for the instructor.
    </p>
  </div>

  <!-- FAQ 2 -->
  <div class="p-5 rounded-2xl bg-card border border-border shadow-sm space-y-2">
    <h3 class="text-sm font-bold text-foreground pt-0">2. Can a fast, skilled touch-typist be falsely flagged as a mechanical transcriber?</h3>
    <p class="text-muted-foreground leading-relaxed">
      No. Skilled touch-typists produce high burst speeds (70–110+ WPM), but their typing is still governed by the cognitive demands of original thought. A fast typist composing an authentic essay exhibits high IKI variance, deep planning pauses (2–15+ seconds) at clause and paragraph boundaries, and frequent revision bursts where they backspace, delete phrases, and rearrange sentences. The difference between a fast typist <em>composing</em> and someone <em>copying from a phone</em> lies in the presence of cognitive pauses and structural revisions, not raw speed.
    </p>
  </div>

  <!-- FAQ 3 -->
  <div class="p-5 rounded-2xl bg-card border border-border shadow-sm space-y-2">
    <h3 class="text-sm font-bold text-foreground pt-0">3. What if a student drafts their essay by hand in a notebook and then types it into the computer?</h3>
    <p class="text-muted-foreground leading-relaxed">
      If a student types up handwritten notes, their telemetry will look similar to transcription (linear entry with few conceptual revisions). However, Checkmark&apos;s multi-factor approach prevents unfair penalties. During the Phase 3 conference, the student simply presents their dated handwritten notebook or outline. The teacher can inspect the notes, verify that the handwriting matches the student&apos;s work, and mark the Checkmark report as <em>Resolved</em> with full credit.
    </p>
  </div>

  <!-- FAQ 4 -->
  <div class="p-5 rounded-2xl bg-card border border-border shadow-sm space-y-2">
    <h3 class="text-sm font-bold text-foreground pt-0">4. How does writing telemetry protect non-native English speakers (ESL/ELL)?</h3>
    <p class="text-muted-foreground leading-relaxed">
      Static AI detectors frequently produce false positives on ESL/ELL students because their vocabulary can be formal, repetitive, or structurally uniform. Checkmark&apos;s Essay Playback™ protects these students by shifting the focus from statistical text properties to authentic drafting effort. An ESL student&apos;s playback will show authentic composing struggle: extended pauses while consulting dictionaries, recursive phrase rewrites, and organic P-bursts—providing definitive proof of genuine authorship.
    </p>
  </div>

  <!-- FAQ 5 -->
  <div class="p-5 rounded-2xl bg-card border border-border shadow-sm space-y-2">
    <h3 class="text-sm font-bold text-foreground pt-0">5. Does Checkmark store or train AI models on student essays?</h3>
    <p class="text-muted-foreground leading-relaxed">
      <strong>No.</strong> Checkmark maintains a strict zero-retention and zero-training policy. Student submissions are never used to train public or proprietary Large Language Models. Checkmark is fully compliant with <strong>FERPA</strong> and <strong>COPPA</strong>, and all telemetry data and submission files are encrypted in transit and at rest within secure cloud infrastructure.
    </p>
  </div>

  <!-- FAQ 6 -->
  <div class="p-5 rounded-2xl bg-card border border-border shadow-sm space-y-2">
    <h3 class="text-sm font-bold text-foreground pt-0">6. How does Checkmark integrate with Canvas LMS and Buzz LMS?</h3>
    <p class="text-muted-foreground leading-relaxed">
      Checkmark integrates natively into <a href="/services/integrations/canvas-lms" class="text-teal-600 dark:text-teal-400 underline font-semibold">Canvas LMS</a> (via LTI 1.3 Advantage) and Buzz LMS. Instructors can view multi-factor reports and scrub Essay Playback™ timelines directly within <strong>Canvas SpeedGrader</strong> or the Buzz assignment evaluation interface. Furthermore, grades and quote-anchored rubric feedback generated by Checkmark&apos;s AI Autograder can be synced straight back to the LMS gradebook with a single click.
    </p>
  </div>

  <!-- FAQ 7 -->
  <div class="p-5 rounded-2xl bg-card border border-border shadow-sm space-y-2">
    <h3 class="text-sm font-bold text-foreground pt-0">7. What should a teacher do if a student denies transcribing from a second screen despite a flat velocity curve?</h3>
    <p class="text-muted-foreground leading-relaxed">
      The educator should use the 4-Phase Restorative Protocol. Share your screen, open Essay Playback™, and ask the student to explain specific conceptual decisions at key timestamps. You can ask the student to define specialized vocabulary appearing in the essay, explain the historical context of a claim, or recreate a short paragraph on the spot during office hours. If the student genuinely understands and authored the material, they will easily demonstrate their knowledge in conversation; if they transcribed it without understanding, their inability to explain the text will guide an appropriate educational resolution.
    </p>
  </div>
</div>
`;

type PageProps = {
  params?: Promise<Record<string, string | string[] | undefined>>;
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
};

export default async function Page(props: PageProps) {
  const searchParams = await props.searchParams;
  const refValue = typeof searchParams?.ref === 'string' ? searchParams.ref : undefined;

  return (
    <ArticleLayout
      meta={meta}
      section="learning"
      currentSlug="2026/8/how-writing-telemetry-visualizes-revision-bursts-versus-mechanical-retyping-in-student-essays"
      refValue={refValue}
    >
      <article
        className="lg:col-span-3 text-base leading-7 tracking-normal space-y-5 [&_p]:text-muted-foreground [&_h2]:pt-4 [&_h2]:text-2xl [&_h2]:font-semibold [&_h2]:tracking-tight [&_h3]:pt-4 [&_h3]:text-xl [&_h3]:font-semibold [&_h3]:tracking-tight [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-2 [&_ol]:list-decimal [&_ol]:pl-6 [&_ol]:space-y-2 [&_blockquote]:border-l-4 [&_blockquote]:border-primary [&_blockquote]:pl-4 [&_blockquote]:italic [&_blockquote]:text-muted-foreground [&_a]:text-primary [&_a]:underline [&_img]:rounded-xl [&_img]:my-6 [&_code]:bg-muted [&_code]:px-1 [&_code]:py-0.5 [&_code]:rounded [&_code]:text-sm"
        dangerouslySetInnerHTML={{ __html: bodyHtml }}
      />
    </ArticleLayout>
  );
}
